version: "3.0"

services:
  visualizer:
    image: dockersamples/visualizer
    ports:
      - 8087:8080/tcp
    deploy:
      placements:
      - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
